language: python
python:
    - "2.7"
    - "3.2"
    - "pypy"
install:
    - pip install --use-mirrors nose
    - pip install --use-mirrors coverage
    - pip install -e .
before_install:
    - wget https://dl.dropboxusercontent.com/u/852780/mock-toolchain.tar.gz
    - tar xzf mock-toolchain.tar.gz
script:
    - nosetests sketchduino/tests/commands.py --with-coverage --cover-package=sketchduino